# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"
  config.vm.hostname = "ansiblecontrolhost"
  
  config.vm.provider "virtualbox" do |vb|  
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", path: "bootstrap.sh"

end
