# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"
  config.vm.hostname = "wordpressdev"
  
  config.vm.network :forwarded_port, guest: 80, host: 80
  
  config.vm.provider "virtualbox" do |vb|  
    vb.memory = "1024"
  end
  
  
  config.vm.synced_folder "src/theme/", "/var/www/html/wp-content/themes/devtheme", owner: "www-data", group: "www-data"  
  
  config.vm.provision "shell", path: "bootstrap.sh"

end
